#!/usr/bin/env bash
#
# generate-feed.sh — Build an Atom XML feed from articles/*.md
#
# Usage: bash scripts/generate-feed.sh [repo_slug]
#   repo_slug: GitHub owner/repo (default: auto-detected from git remote)
#
# Output: articles/feed.xml
#

set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || echo ".")"
ARTICLES_DIR="$REPO_ROOT/articles"
OUTPUT_FILE="$ARTICLES_DIR/feed.xml"

# Determine repo slug (owner/repo)
if [[ -n "${1:-}" ]]; then
    REPO_SLUG="$1"
else
    REMOTE_URL="$(git -C "$REPO_ROOT" remote get-url origin 2>/dev/null || echo "")"
    if [[ "$REMOTE_URL" =~ github\.com[:/]([^/]+/[^/.]+) ]]; then
        REPO_SLUG="${BASH_REMATCH[1]}"
    else
        REPO_SLUG="aaronjmars/aeon"
    fi
fi

BASE_URL="https://github.com/$REPO_SLUG/blob/main/articles"
RAW_URL="https://raw.githubusercontent.com/$REPO_SLUG/main/articles"
FEED_URL="$RAW_URL/feed.xml"
FEED_TITLE="Aeon Articles"
FEED_SUBTITLE="Articles generated by Aeon — autonomous agent powered by Claude Code"
AUTHOR_NAME="Aeon"

# XML-escape a string
xml_escape() {
    local s="$1"
    s="${s//&/&amp;}"
    s="${s//</&lt;}"
    s="${s//>/&gt;}"
    s="${s//\"/&quot;}"
    s="${s//\'/&apos;}"
    printf '%s' "$s"
}

# Extract date from filename (YYYY-MM-DD) or fall back to file modification time
extract_date() {
    local file="$1"
    local basename
    basename="$(basename "$file" .md)"
    # Try to find a YYYY-MM-DD pattern anywhere in the filename
    if [[ "$basename" =~ ([0-9]{4}-[0-9]{2}-[0-9]{2}) ]]; then
        echo "${BASH_REMATCH[1]}T00:00:00Z"
    else
        # Fall back to git commit date or file mtime
        local git_date
        git_date="$(git -C "$REPO_ROOT" log -1 --format="%aI" -- "$file" 2>/dev/null || echo "")"
        if [[ -n "$git_date" ]]; then
            echo "$git_date"
        else
            date -r "$file" -u "+%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u "+%Y-%m-%dT%H:%M:%SZ"
        fi
    fi
}

# Extract title from first # heading
extract_title() {
    local file="$1"
    local title=""
    while IFS= read -r line; do
        # Skip frontmatter
        if [[ "$line" == "---" ]]; then
            # Read until closing ---
            while IFS= read -r line; do
                [[ "$line" == "---" ]] && break
            done
            continue
        fi
        # First # heading is the title
        if [[ "$line" =~ ^#[[:space:]]+(.*) ]]; then
            title="${BASH_REMATCH[1]}"
            break
        fi
    done < "$file"
    if [[ -z "$title" ]]; then
        title="$(basename "$file" .md)"
    fi
    echo "$title"
}

# Extract first paragraph (non-empty, non-heading line after title)
extract_summary() {
    local file="$1"
    local found_title=false
    local in_frontmatter=false
    local summary=""
    while IFS= read -r line; do
        # Handle frontmatter
        if [[ "$in_frontmatter" == false && "$line" == "---" ]]; then
            in_frontmatter=true
            continue
        fi
        if [[ "$in_frontmatter" == true ]]; then
            [[ "$line" == "---" ]] && in_frontmatter=false
            continue
        fi
        # Skip blank lines and headings before finding content
        [[ -z "$line" ]] && continue
        # Skip the title heading
        if [[ "$found_title" == false && "$line" =~ ^#[[:space:]] ]]; then
            found_title=true
            continue
        fi
        # Skip any subsequent headings
        [[ "$line" =~ ^#+ ]] && continue
        # First non-empty, non-heading line is the summary
        summary="$line"
        break
    done < "$file"
    echo "$summary"
}

# --- Main ---

# Collect article files (exclude .gitkeep and feed.xml)
mapfile -t article_files < <(
    find "$ARTICLES_DIR" -maxdepth 1 -name "*.md" -type f 2>/dev/null | sort -r
)

if [[ ${#article_files[@]} -eq 0 ]]; then
    echo "No articles found in $ARTICLES_DIR — writing empty feed."
fi

# Determine the most recent update time for the feed
latest_updated=""
for f in "${article_files[@]}"; do
    d="$(extract_date "$f")"
    if [[ -z "$latest_updated" || "$d" > "$latest_updated" ]]; then
        latest_updated="$d"
    fi
done
[[ -z "$latest_updated" ]] && latest_updated="$(date -u "+%Y-%m-%dT%H:%M:%SZ")"

# Build the feed
{
    cat <<HEADER
<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <title>$(xml_escape "$FEED_TITLE")</title>
  <subtitle>$(xml_escape "$FEED_SUBTITLE")</subtitle>
  <link href="$(xml_escape "$FEED_URL")" rel="self" type="application/atom+xml"/>
  <link href="$(xml_escape "$BASE_URL")" rel="alternate" type="text/html"/>
  <id>$(xml_escape "$FEED_URL")</id>
  <updated>$latest_updated</updated>
  <author>
    <name>$(xml_escape "$AUTHOR_NAME")</name>
  </author>
  <generator>Aeon RSS Feed Generator</generator>
HEADER

    for file in "${article_files[@]}"; do
        filename="$(basename "$file")"
        title="$(extract_title "$file")"
        date_str="$(extract_date "$file")"
        summary="$(extract_summary "$file")"
        article_url="$BASE_URL/$filename"
        entry_id="$RAW_URL/$filename"

        cat <<ENTRY
  <entry>
    <title>$(xml_escape "$title")</title>
    <link href="$(xml_escape "$article_url")" rel="alternate" type="text/html"/>
    <id>$(xml_escape "$entry_id")</id>
    <updated>$date_str</updated>
    <summary>$(xml_escape "$summary")</summary>
  </entry>
ENTRY
    done

    echo "</feed>"
} > "$OUTPUT_FILE"

echo "Feed written to $OUTPUT_FILE (${#article_files[@]} articles)"
